name: elmed219-2025
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - git
  - pip
  - pip:
    - gdown
    - pycaret
    - shap
    - catboost
    - xgboost
    - pyreadstat
    - statsmodels
    - pingouin
    - voila
    - scikit-learn
    - scikit-image
    - SimpleITK
    - itkwidgets
    - imageio
    - dcm2niix
    - readimc
    - tiffile
    - nilearn
    - networkx
    - dipy
    - openpyxl
    - pygraphviz  # Lab0-02-network-tutorial
    - pydot       # Lab0-02-network-tutorial

## Configure the Conda-environment elmed219-2025 for data analysis, computational imaging and modeling (only once):
# conda env create -f environment.yml

## To make a ELMED219-2025 kernel (optional):
# python -m ipykernel install --user --name elmed219-2025 --display-name "ELMED219-2025"

## To activate the elmed219-2025 conda environment:
# conda activate elmed219-2025

## To update the elmed219-2025 conda environment:
# conda env update -f environment.yml

## To remove and reinstall the elmed219-2025 environment (if installation problems):
# conda deactivate
# conda env remove -n elmed219-2025
# conda env create -f environment.yml
