name: pycaret
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - pip
  - pip:
    - pycaret
    - xgboost>=2.0.0
    - catboost>=1.2.5
    - kmodes>=0.11.1
    - mlxtend>=0.19.0
    - statsforecast<1.8.0,>1.6
    - scikit-learn-intelex>=2023.0.1; platform_machine == 'x86_64' or platform_machine == 'AMD64'
    - ydata-profiling
    - gradio
    - explainerdashboard
